### ISSUE TITLE
BoxfitSerializer unresolved

### ISSUE THREAD

**Issue by memorex386** [ManueGE/Boxfit#1]
I've done a clean/rebuild project and gradle sync but still do not see this class.  Im using Kotlin, although I couldnt get it to work in Java either.  For Kotlin I switch to kapt instead of annotationProcessor.  Any advice?

**Comment by memorex386** [comment]
ah got it, I wasn't annotating @BoxClass so it wasn't generating.  doh

**Comment by mitfik** [comment]
@ManueGE I am having same issue as above but can not get it through. 
My setup: kotlin with objectbox and retrofit. 
I added all annotation in my entity class from objectbox:  `@BoxfitClass` and `@BoxfitField` but the `BoxfitSerializer` class is not generated. Tried to rebuild/invalidate cache/clean nothing works. 

Any idea how I could debug that issue and find out why the class is not generated?
