### ISSUE TITLE
Kotlin and public fields

### ISSUE THREAD

**Issue by memorex386** [ManueGE/Boxfit#2]
First off, Boxfit has been great!  But the biggest issue I've seen is with Kotlin and public fields.  If I write code like so :

`@BoxfitField("DateCreated") var dateCreated : String = ""`

I get a "Fields cannot be private" error when I try to compile.  

The workaround I've implemented is a combination of the `@JVMField` annotation and the `lateinit` modifier like so :

`@JVMField
@BoxfitField("DateCreated")
var dateCreated : String = ""`

`@BoxfitField("DateCreated") lateinit dateCreated : String`

This creates some limitation as it does not allow the variable to be overridden, no custom getters and setters, and limits the ability to load directly into the constructor - particularity for data class types.

Just hope this info help and thanks again for a great library!

**Comment by ManueGE** [comment]
Thanks for using Boxfit :)

Honestly, I am a little out from the Kotlin world, but I will try to give it a look during the weekend. Maybe I can find a way to fix this. 

I will update the issue if I find something. 

Regards.

**Comment by ManueGE** [comment]
Just took a look and it is much more difficult than I expected. I would need to generate the serializers for Kotlin classes in Kotlin, and I am not sure about how they'll work with the java classes. 

I will find a gap for it, but I am afraid it will be anytime soon, sorry :(

**Comment by memorex386** [comment]
Ill check it out too, but for now it works in Kotlin with what I listed above.  Thanks @ManueGE

**Comment by ManueGE** [comment]
It should be fixed in [release 0.0.2](https://github.com/ManueGE/Boxfit/releases/tag/0.0.2). 

I'm closing the issue, if you have additional problems, please open a new one :)
