### ISSUE TITLE
 AndroidTest build failed

### ISSUE THREAD

**Issue by yc86209** [ManueGE/Boxfit#4]
Hi, when I run the Android Test, I got some error issues and build failed.

>Error output
```FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':app:preDebugAndroidTestBuild'.
Conflict with dependency 'org.bouncycastle:bcprov-jdk15on' in project ':app'. 
Resolved versions for app (1.50) and test app (1.52) differ. 
See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.
```
>Waring

```
warning: Supported source version 'RELEASE_7' from annotation processor 
'com.manuege.boxfit_processor.processor.BoxfitProcessor' less than -source '1.8'
```
Thanks!

**Comment by ManueGE** [comment]
Hi!

Despite the warning, I am not sure it is a Boxfit issue. The warning is just a warning, shouldn't bring any error. 

Could you check the steps from here (https://stackoverflow.com/a/28999596/4912616) and confirm that this is a Boxfit issue?

Thanks :)

**Comment by yc86209** [comment]
I found out why the build failed.
```
androidTestImplementation 'org.robolectric:robolectric:3.8'
```
It leads to conflict.
