### ISSUE TITLE
Could not find IntegerSerializer

### ISSUE THREAD

**Issue by benjaminledet** [ManueGE/Boxfit#6]
Hi, here is my class :

<img width="552" alt="capture d ecran 2018-07-09 a 16 44 31" src="https://user-images.githubusercontent.com/23617972/42457285-61cf20a4-8397-11e8-8977-f85edfd2366b.png">

I get this error : 

<img width="839" alt="capture d ecran 2018-07-09 a 16 45 57" src="https://user-images.githubusercontent.com/23617972/42457396-a95f6c12-8397-11e8-8c5d-21486d412b2e.png">

And the file : 
<img width="598" alt="capture d ecran 2018-07-09 a 16 47 47" src="https://user-images.githubusercontent.com/23617972/42457474-dd525458-8397-11e8-8304-eefef3aeb0fe.png">

I dont understand what I need to do, thanks.

**Comment by ManueGE** [comment]
Sadly this a case I haven't think of. Since `ObjectBox` doesn't allow directly a `List` of primitive types as `Int` or `Strings`, I didn't take this case in account. I think I can figure out something, but I am not sure when I will have time for this. 

I'm so sorry, I will keep the issue updated if I find any solution.

**Comment by ManueGE** [comment]
Should be fixed in version `0.0.5`.

**Comment by benjaminledet** [comment]
Hi, thanks for your reactivity, you rock.
But there is a little bug in Kotlin : 

<img width="530" alt="capture d ecran 2018-07-10 a 08 30 20" src="https://user-images.githubusercontent.com/23617972/42493018-82d861fa-841b-11e8-8e01-1a68a1edd42f.png">

<img width="188" alt="capture d ecran 2018-07-10 a 08 30 28" src="https://user-images.githubusercontent.com/23617972/42493023-852b5a8e-841b-11e8-9e09-dc534d523bc1.png">

**Comment by ManueGE** [comment]
Well, I'm afraid you'll need to set `availableDays` as `var` instead of `val`. `Boxfit` change the values of the object, so `val` is not supported.

**Comment by benjaminledet** [comment]
Sorry my mistake! It's a stupid error I didn't realized that I'd put it to val.
